name: Release
on:
  release:
    types: [created]
env:
  node_version: 14.x
  pnpm_version: '5'
jobs:
  npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-pnpm-store-${{ env.node_version }}-${{ env.pnpm_version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-pnpm-store-${{ env.node_version }}-${{ env.pnpm_version }}-
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: ${{ env.pnpm_version }}
          run_install: true
      - run: make rebuild
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
