name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  node_version: 16.x
  pnpm_version: '7'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm_version }}
          run_install: false
      - id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: |
          pnpm install
          make all
